"""add sales and consignment

Revision ID: 376116e81be6
Revises: 69f27228600f
Create Date: 2026-06-05 18:58:11.215047

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "376116e81be6"
down_revision: str | Sequence[str] | None = "69f27228600f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sales",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("clerk_user_id", sa.Integer(), nullable=False),
        sa.Column("buyer_contact_id", sa.Integer(), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=12, scale=0), nullable=False),
        sa.Column("tax", sa.Numeric(precision=12, scale=0), nullable=False),
        sa.Column("total", sa.Numeric(precision=12, scale=0), nullable=False),
        sa.Column(
            "payment_method",
            sa.Enum(
                "CASH", name="paymentmethod", native_enum=False, create_constraint=True, length=30
            ),
            server_default="CASH",
            nullable=False,
        ),
        sa.Column(
            "invoice_status",
            sa.Enum(
                "NOT_ISSUED",
                "ISSUED",
                "VOID",
                "ALLOWANCE",
                name="saleinvoicestatus",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            server_default="NOT_ISSUED",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "COMPLETED",
                "RETURNED",
                name="salestatus",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            server_default="COMPLETED",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["buyer_contact_id"],
            ["contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["clerk_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sales_store_id"), "sales", ["store_id"], unique=False)
    op.create_table(
        "consignment_settlements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("serialized_item_id", sa.Integer(), nullable=False),
        sa.Column("sale_id", sa.Integer(), nullable=False),
        sa.Column("gross", sa.Numeric(precision=12, scale=0), nullable=False),
        sa.Column("commission_pct", sa.Integer(), nullable=False),
        sa.Column("commission_amount", sa.Numeric(precision=12, scale=0), nullable=False),
        sa.Column("payout_amount", sa.Numeric(precision=12, scale=0), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PAID",
                "CANCELLED",
                name="consignmentsettlementstatus",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_by", sa.Integer(), nullable=True),
        sa.Column("reclaim_needed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paid_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sale_id"],
            ["sales.id"],
        ),
        sa.ForeignKeyConstraint(
            ["serialized_item_id"],
            ["serialized_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_consignment_settlements_sale_id"),
        "consignment_settlements",
        ["sale_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consignment_settlements_serialized_item_id"),
        "consignment_settlements",
        ["serialized_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consignment_settlements_store_id"),
        "consignment_settlements",
        ["store_id"],
        unique=False,
    )
    op.create_table(
        "sale_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("sale_id", sa.Integer(), nullable=False),
        sa.Column(
            "line_type",
            sa.Enum(
                "SERIALIZED",
                "CATALOG",
                "BULK_LOT",
                name="salelinetype",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("serialized_item_id", sa.Integer(), nullable=True),
        sa.Column("catalog_product_id", sa.Integer(), nullable=True),
        sa.Column("bulk_lot_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(length=150), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=0), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=12, scale=0), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bulk_lot_id"],
            ["bulk_lots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["catalog_product_id"],
            ["catalog_products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sale_id"],
            ["sales.id"],
        ),
        sa.ForeignKeyConstraint(
            ["serialized_item_id"],
            ["serialized_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sale_lines_sale_id"), "sale_lines", ["sale_id"], unique=False)
    op.create_index(op.f("ix_sale_lines_store_id"), "sale_lines", ["store_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sale_lines_store_id"), table_name="sale_lines")
    op.drop_index(op.f("ix_sale_lines_sale_id"), table_name="sale_lines")
    op.drop_table("sale_lines")
    op.drop_index(op.f("ix_consignment_settlements_store_id"), table_name="consignment_settlements")
    op.drop_index(
        op.f("ix_consignment_settlements_serialized_item_id"), table_name="consignment_settlements"
    )
    op.drop_index(op.f("ix_consignment_settlements_sale_id"), table_name="consignment_settlements")
    op.drop_table("consignment_settlements")
    op.drop_index(op.f("ix_sales_store_id"), table_name="sales")
    op.drop_table("sales")
    # ### end Alembic commands ###
