"""add inventory

Revision ID: 6941c06a8cab
Revises: e7687691967e
Create Date: 2026-06-03 21:51:46.902993

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6941c06a8cab"
down_revision: str | Sequence[str] | None = "e7687691967e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("store_id", "name", name="uq_brands_store_name"),
    )
    op.create_index(op.f("ix_brands_store_id"), "brands", ["store_id"], unique=False)
    op.create_table(
        "bulk_lots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("lot_code", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("brand_id", sa.Integer(), nullable=True),
        sa.Column(
            "grade",
            sa.Enum(
                "S",
                "A",
                "B",
                "C",
                "D",
                "E",
                name="grade",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("consignor_id", sa.Integer(), nullable=True),
        sa.Column("acquisition_cost", sa.Numeric(precision=12, scale=0), nullable=False),
        sa.Column(
            "acquisition_basis",
            sa.Enum(
                "WEIGHT",
                "BAG",
                "UNSPECIFIED",
                name="bulkacquisitionbasis",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=0), nullable=False),
        sa.Column("total_qty", sa.Integer(), nullable=False),
        sa.Column("remaining_qty", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ON_SALE",
                "SOLD_OUT",
                "WRITTEN_OFF",
                name="bulklotstatus",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            server_default="ON_SALE",
            nullable=False,
        ),
        sa.Column("acquisition_id", sa.Integer(), nullable=True),
        sa.Column(
            "intake_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
        ),
        sa.ForeignKeyConstraint(
            ["consignor_id"],
            ["contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bulk_lots_lot_code"), "bulk_lots", ["lot_code"], unique=True)
    op.create_index(op.f("ix_bulk_lots_store_id"), "bulk_lots", ["store_id"], unique=False)
    op.create_table(
        "catalog_products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("brand_id", sa.Integer(), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=0), nullable=False),
        sa.Column("quantity_on_hand", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("reorder_point", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalog_products_store_id"), "catalog_products", ["store_id"], unique=False
    )
    op.create_table(
        "product_models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("brand_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("store_id", "name", name="uq_product_models_store_name"),
    )
    op.create_index(
        op.f("ix_product_models_brand_id"), "product_models", ["brand_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_models_store_id"), "product_models", ["store_id"], unique=False
    )
    op.create_table(
        "serialized_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("item_code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("brand_id", sa.Integer(), nullable=True),
        sa.Column("product_model_id", sa.Integer(), nullable=True),
        sa.Column(
            "grade",
            sa.Enum(
                "S",
                "A",
                "B",
                "C",
                "D",
                "E",
                name="grade",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column(
            "ownership_type",
            sa.Enum(
                "OWNED",
                "CONSIGNMENT",
                name="ownershiptype",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("acquisition_cost", sa.Numeric(precision=12, scale=0), nullable=True),
        sa.Column("consignor_id", sa.Integer(), nullable=True),
        sa.Column("commission_pct", sa.Integer(), nullable=True),
        sa.Column("listed_price", sa.Numeric(precision=12, scale=0), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "IN_STOCK",
                "SOLD",
                "RETURNED_TO_CONSIGNOR",
                "WRITTEN_OFF",
                name="serializeditemstatus",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            server_default="IN_STOCK",
            nullable=False,
        ),
        sa.Column("acquisition_id", sa.Integer(), nullable=True),
        sa.Column(
            "intake_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sold_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
        ),
        sa.ForeignKeyConstraint(
            ["consignor_id"],
            ["contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_model_id"],
            ["product_models.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_serialized_items_item_code"), "serialized_items", ["item_code"], unique=True
    )
    op.create_index(
        op.f("ix_serialized_items_store_id"), "serialized_items", ["store_id"], unique=False
    )
    op.create_table(
        "stock_movements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column(
            "item_kind",
            sa.Enum(
                "SERIALIZED",
                "CATALOG",
                "BULK_LOT",
                name="itemkind",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("serialized_item_id", sa.Integer(), nullable=True),
        sa.Column("catalog_product_id", sa.Integer(), nullable=True),
        sa.Column("bulk_lot_id", sa.Integer(), nullable=True),
        sa.Column(
            "direction",
            sa.Enum(
                "IN",
                "OUT",
                "ADJUST",
                name="stockdirection",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "ACQUISITION",
                "PURCHASE",
                "SALE",
                "RETURN",
                "CONSIGN_RETURN",
                "WRITE_OFF",
                "STOCKTAKE",
                name="stockreason",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("ref_type", sa.String(length=50), nullable=True),
        sa.Column("ref_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bulk_lot_id"],
            ["bulk_lots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["catalog_product_id"],
            ["catalog_products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["serialized_item_id"],
            ["serialized_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stock_movements_store_id"), "stock_movements", ["store_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stock_movements_store_id"), table_name="stock_movements")
    op.drop_table("stock_movements")
    op.drop_index(op.f("ix_serialized_items_store_id"), table_name="serialized_items")
    op.drop_index(op.f("ix_serialized_items_item_code"), table_name="serialized_items")
    op.drop_table("serialized_items")
    op.drop_index(op.f("ix_product_models_store_id"), table_name="product_models")
    op.drop_index(op.f("ix_product_models_brand_id"), table_name="product_models")
    op.drop_table("product_models")
    op.drop_index(op.f("ix_catalog_products_store_id"), table_name="catalog_products")
    op.drop_table("catalog_products")
    op.drop_index(op.f("ix_bulk_lots_store_id"), table_name="bulk_lots")
    op.drop_index(op.f("ix_bulk_lots_lot_code"), table_name="bulk_lots")
    op.drop_table("bulk_lots")
    op.drop_index(op.f("ix_brands_store_id"), table_name="brands")
    op.drop_table("brands")
    # ### end Alembic commands ###
