"""add contacts

Revision ID: e7687691967e
Revises: 62eb8579d1c2
Create Date: 2026-06-03 21:31:26.945647

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e7687691967e"
down_revision: str | Sequence[str] | None = "62eb8579d1c2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("national_id_enc", sa.String(length=255), nullable=True),
        sa.Column("national_id_blind_index", sa.String(length=64), nullable=True),
        sa.Column(
            "roles",
            postgresql.ARRAY(sa.String(length=20)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("member_points", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("default_carrier_type", sa.String(length=10), nullable=True),
        sa.Column("default_carrier_id", sa.String(length=64), nullable=True),
        sa.Column("source_note", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "store_id", "national_id_blind_index", name="uq_contacts_store_blind_index"
        ),
    )
    op.create_index(
        op.f("ix_contacts_national_id_blind_index"),
        "contacts",
        ["national_id_blind_index"],
        unique=False,
    )
    op.create_index(op.f("ix_contacts_phone"), "contacts", ["phone"], unique=False)
    op.create_index(op.f("ix_contacts_store_id"), "contacts", ["store_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_contacts_store_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_phone"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_national_id_blind_index"), table_name="contacts")
    op.drop_table("contacts")
    # ### end Alembic commands ###
