/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/acquisitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Acquisition */
        post: operations["createAcquisition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/acquisitions/{acquisition_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Acquisition */
        get: operations["getAcquisition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bulk-lots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bulk Lots */
        get: operations["listBulkLots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cash-sessions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current Cash Session */
        get: operations["getCurrentCashSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cash-sessions/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open Cash Session */
        post: operations["openCashSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cash-sessions/{session_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Cash Session */
        post: operations["closeCashSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cash-sessions/{session_id}/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Cash Movement */
        post: operations["recordCashMovement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog-products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Catalog */
        get: operations["listCatalogProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contacts */
        get: operations["listContacts"];
        put?: never;
        /** Create Contact */
        post: operations["createContact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lookup Contact */
        post: operations["lookupContact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/{contact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contact */
        get: operations["getContact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/{contact_id}/national-id": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reveal National Id */
        get: operations["revealContactNationalId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sales */
        get: operations["listSales"];
        put?: never;
        /** Create Sale */
        post: operations["createSale"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sales/{sale_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sale */
        get: operations["getSale"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sales/{sale_id}/print-detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Print Sale Detail */
        post: operations["printSaleDetail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sales/{sale_id}/void": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Void Sale */
        post: operations["voidSale"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/serialized-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Serialized */
        get: operations["listSerializedItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/serialized-items/by-code/{item_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Serialized By Code
         * @description POS 掃碼查件：以 item_code 取序號品（他店/不存在一律 404，不洩漏跨店資料）。
         */
        get: operations["getSerializedItemByCode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Settings */
        patch: operations["updateSettings"];
        trace?: never;
    };
    "/api/v1/stores/{store_id}/receipt-header": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Receipt Header
         * @description 回傳指定門市的收據抬頭；門市不存在 → 404。
         */
        get: operations["getStoreReceiptHeader"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AcquisitionCreate
         * @description 收購單輸入。BUYOUT/CONSIGNMENT 走 items；BULK_LOT 走 lot。
         */
        AcquisitionCreate: {
            /** Contact Id */
            contact_id: number;
            /** Items */
            items?: components["schemas"]["AcquisitionItemIn"][] | null;
            lot?: components["schemas"]["AcquisitionLotIn"] | null;
            /** Note */
            note?: string | null;
            type: components["schemas"]["AcquisitionType"];
        };
        /**
         * AcquisitionItemIn
         * @description 序號單品入庫明細（BUYOUT/CONSIGNMENT）。grade 限 S-D（E 走散裝）。
         */
        AcquisitionItemIn: {
            /** Acquisition Cost */
            acquisition_cost?: number | string | null;
            /** Brand Id */
            brand_id?: number | null;
            /** Commission Pct */
            commission_pct?: number | null;
            grade: components["schemas"]["Grade"];
            /** Listed Price */
            listed_price: number | string;
            /** Name */
            name: string;
            /** Product Model Id */
            product_model_id?: number | null;
        };
        /**
         * AcquisitionLotIn
         * @description E 級散裝批入庫（BULK_LOT）。
         */
        AcquisitionLotIn: {
            acquisition_basis: components["schemas"]["BulkAcquisitionBasis"];
            /** Acquisition Cost */
            acquisition_cost: number | string;
            /** Brand Id */
            brand_id?: number | null;
            /** Label */
            label?: string | null;
            /** Name */
            name: string;
            /** Total Qty */
            total_qty: number;
            /** Unit Price */
            unit_price: number | string;
        };
        /**
         * AcquisitionRead
         * @description 收購單查詢輸出。
         */
        AcquisitionRead: {
            /** Clerk User Id */
            clerk_user_id: number;
            /** Contact Id */
            contact_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Note */
            note: string | null;
            /** Store Id */
            store_id: number;
            /** Total Cash Paid */
            total_cash_paid: string | null;
            type: components["schemas"]["AcquisitionType"];
        };
        /**
         * AcquisitionResult
         * @description 收購成功結果：回傳可辨識的收購單號與待列印識別碼。
         */
        AcquisitionResult: {
            /** Acquisition Id */
            acquisition_id: number;
            /** Contact Id */
            contact_id: number;
            /** Item Codes */
            item_codes: string[];
            /** Lot Code */
            lot_code: string | null;
            /** Total Cash Paid */
            total_cash_paid: string | null;
            type: components["schemas"]["AcquisitionType"];
        };
        /**
         * AcquisitionType
         * @description 收購/寄售入庫單類型。
         *
         *     BUYOUT 買斷（建序號品、付現）；CONSIGNMENT 寄售（建序號品、不付現）；
         *     BULK_LOT E 級散裝（建散裝批、付現）。
         * @enum {string}
         */
        AcquisitionType: "BUYOUT" | "CONSIGNMENT" | "BULK_LOT";
        /**
         * BulkAcquisitionBasis
         * @description 散裝批收購計價基礎。
         * @enum {string}
         */
        BulkAcquisitionBasis: "WEIGHT" | "BAG" | "UNSPECIFIED";
        /**
         * BulkLotRead
         * @description 散裝堆輸出（POS 明確選堆/庫存列表；含收購成本與售出進度）。
         */
        BulkLotRead: {
            acquisition_basis: components["schemas"]["BulkAcquisitionBasis"];
            /** Acquisition Cost */
            acquisition_cost: string;
            /** Brand Id */
            brand_id: number | null;
            grade: components["schemas"]["Grade"];
            /** Id */
            id: number;
            /** Label */
            label: string | null;
            /** Lot Code */
            lot_code: string;
            /** Name */
            name: string;
            /** Remaining Qty */
            remaining_qty: number;
            status: components["schemas"]["BulkLotStatus"];
            /** Store Id */
            store_id: number;
            /** Total Qty */
            total_qty: number;
            /** Unit Price */
            unit_price: string;
        };
        /**
         * BulkLotStatus
         * @description 散裝批狀態。
         * @enum {string}
         */
        BulkLotStatus: "ON_SALE" | "SOLD_OUT" | "WRITTEN_OFF";
        /**
         * CashMovementCreateRequest
         * @description 記一筆現金異動（MANUAL_ADJUST 可正可負；其餘類型非負）。
         */
        CashMovementCreateRequest: {
            /** Amount */
            amount: number | string;
            /** Note */
            note?: string | null;
            type: components["schemas"]["CashMovementType"];
        };
        /**
         * CashMovementRead
         * @description 現金異動輸出。
         */
        CashMovementRead: {
            /** Amount */
            amount: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Ref Id */
            ref_id: number | null;
            /** Ref Type */
            ref_type: string | null;
            /** Session Id */
            session_id: number;
            /** Store Id */
            store_id: number;
            type: components["schemas"]["CashMovementType"];
        };
        /**
         * CashMovementType
         * @description 現金異動類型。
         *
         *     SALE_IN 進帳；BUYOUT_OUT / CONSIGNMENT_PAYOUT_OUT 出帳；MANUAL_ADJUST 可正可負。
         * @enum {string}
         */
        CashMovementType: "SALE_IN" | "BUYOUT_OUT" | "CONSIGNMENT_PAYOUT_OUT" | "MANUAL_ADJUST";
        /**
         * CashSessionCloseRequest
         * @description 結帳：點數後的實際現金。
         */
        CashSessionCloseRequest: {
            /** Counted Amount */
            counted_amount: number | string;
        };
        /**
         * CashSessionOpenRequest
         * @description 開帳：期初零用金。
         */
        CashSessionOpenRequest: {
            /** Opening Float */
            opening_float: number | string;
        };
        /**
         * CashSessionRead
         * @description 現金班別輸出。
         */
        CashSessionRead: {
            /** Closed At */
            closed_at: string | null;
            /** Closed By */
            closed_by: number | null;
            /** Counted Amount */
            counted_amount: string | null;
            /** Expected Amount */
            expected_amount: string | null;
            /** Id */
            id: number;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Opened By */
            opened_by: number;
            /** Opening Float */
            opening_float: string;
            status: components["schemas"]["CashSessionStatus"];
            /** Store Id */
            store_id: number;
            /** Variance */
            variance: string | null;
        };
        /**
         * CashSessionStatus
         * @description 現金抽屜班別狀態。
         * @enum {string}
         */
        CashSessionStatus: "OPEN" | "CLOSED";
        /**
         * CatalogProductRead
         * @description 數量型商品輸出（POS 選件/庫存列表）。
         */
        CatalogProductRead: {
            /** Brand Id */
            brand_id: number | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Quantity On Hand */
            quantity_on_hand: number;
            /** Reorder Point */
            reorder_point: number;
            /** Sku */
            sku: string;
            /** Store Id */
            store_id: number;
            /** Unit Price */
            unit_price: string;
        };
        /**
         * ContactCreate
         * @description 建立聯絡人輸入。收購/寄售對象（SELLER/CONSIGNOR）必填 national_id。
         */
        ContactCreate: {
            /** Default Carrier Id */
            default_carrier_id?: string | null;
            /** Default Carrier Type */
            default_carrier_type?: string | null;
            /**
             * Member Points
             * @default 0
             */
            member_points: number;
            /** Name */
            name: string;
            /** National Id */
            national_id?: string | null;
            /** Phone */
            phone?: string | null;
            /** Roles */
            roles?: components["schemas"]["ContactRole"][];
            /** Source Note */
            source_note?: string | null;
        };
        /**
         * ContactLookupRequest
         * @description 以 national_id 精確查重（放 body，避免 national_id 進入 URL / access log）。
         */
        ContactLookupRequest: {
            /** National Id */
            national_id: string;
        };
        /**
         * ContactNationalIdRead
         * @description MANAGER 解密查看的回應（明文，僅此端點回傳）。
         */
        ContactNationalIdRead: {
            /** National Id */
            national_id: string;
        };
        /**
         * ContactRead
         * @description 聯絡人輸出：national_id 一律遮罩，不回明文。
         */
        ContactRead: {
            /** Default Carrier Id */
            default_carrier_id: string | null;
            /** Default Carrier Type */
            default_carrier_type: string | null;
            /** Has National Id */
            has_national_id: boolean;
            /** Id */
            id: number;
            /** Member Points */
            member_points: number;
            /** Name */
            name: string;
            /** National Id Masked */
            national_id_masked: string | null;
            /** Phone */
            phone: string | null;
            /** Roles */
            roles: string[];
            /** Source Note */
            source_note: string | null;
            /** Store Id */
            store_id: number;
        };
        /**
         * ContactRole
         * @description 聯絡人角色（統一主檔可同時具備多重角色）。
         * @enum {string}
         */
        ContactRole: "MEMBER" | "SELLER" | "CONSIGNOR";
        /**
         * Grade
         * @description 成色分級。S-D 走序號單品（serialized_item），E 為散裝批（bulk_lot）。
         * @enum {string}
         */
        Grade: "S" | "A" | "B" | "C" | "D" | "E";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description `/health` 回應。
         */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /**
         * LoginRequest
         * @description 登入請求；長度上限鏡像 users 欄位，避免無意義長字串打到 DB/雜湊。
         */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /**
         * OwnershipType
         * @description 序號品擁有型態。OWNED=買斷，CONSIGNMENT=寄售。
         * @enum {string}
         */
        OwnershipType: "OWNED" | "CONSIGNMENT";
        /**
         * PaymentMethod
         * @description 付款方式。本期僅收現金（docs/02 §1 約束「只收現金」），列舉預留未來擴充。
         * @enum {string}
         */
        PaymentMethod: "CASH";
        /**
         * ReceiptHeaderRead
         * @description 收據／明細聯抬頭（店名/統編/地址/電話/發票字軌資訊）。
         */
        ReceiptHeaderRead: {
            /** Address */
            address: string | null;
            /** Invoice Track Info */
            invoice_track_info: string | null;
            /** Name */
            name: string;
            /** Phone */
            phone: string | null;
            /** Tax Id */
            tax_id: string | null;
        };
        /**
         * SaleCreateRequest
         * @description 結帳請求。idempotency key 走 HTTP 標頭 Idempotency-Key，不在 body。
         */
        SaleCreateRequest: {
            /** Buyer Contact Id */
            buyer_contact_id?: number | null;
            /** Lines */
            lines: components["schemas"]["SaleLineCreateRequest"][];
        };
        /**
         * SaleInvoiceStatus
         * @description 銷售單的開票狀態（sales.invoice_status）。
         *
         *     NOT_ISSUED：einvoice_enabled 關閉或尚未開票（銷售仍完整記錄，§6）；
         *     ISSUED：已開立發票；VOID：已作廢；ALLOWANCE：已折讓。
         * @enum {string}
         */
        SaleInvoiceStatus: "NOT_ISSUED" | "ISSUED" | "VOID" | "ALLOWANCE";
        /**
         * SaleLineCreateRequest
         * @description 單行結帳輸入：SERIALIZED→item_code（qty 固定 1）；CATALOG/BULK_LOT→id + qty。
         */
        SaleLineCreateRequest: {
            /** Bulk Lot Id */
            bulk_lot_id?: number | null;
            /** Catalog Product Id */
            catalog_product_id?: number | null;
            /** Item Code */
            item_code?: string | null;
            line_type: components["schemas"]["SaleLineType"];
            /**
             * Qty
             * @default 1
             */
            qty: number;
        };
        /**
         * SaleLineRead
         * @description 銷售明細輸出。
         */
        SaleLineRead: {
            /** Bulk Lot Id */
            bulk_lot_id: number | null;
            /** Catalog Product Id */
            catalog_product_id: number | null;
            /** Description */
            description: string;
            /** Id */
            id: number;
            /** Line Total */
            line_total: string;
            line_type: components["schemas"]["SaleLineType"];
            /** Qty */
            qty: number;
            /** Serialized Item Id */
            serialized_item_id: number | null;
            /** Unit Price */
            unit_price: string;
        };
        /**
         * SaleLineType
         * @description 銷售明細行的品項種類。
         * @enum {string}
         */
        SaleLineType: "SERIALIZED" | "CATALOG" | "BULK_LOT";
        /**
         * SaleRead
         * @description 銷售單輸出（含明細）。
         */
        SaleRead: {
            /** Buyer Contact Id */
            buyer_contact_id: number | null;
            /** Clerk User Id */
            clerk_user_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            invoice_status: components["schemas"]["SaleInvoiceStatus"];
            /**
             * Lines
             * @default []
             */
            lines: components["schemas"]["SaleLineRead"][];
            payment_method: components["schemas"]["PaymentMethod"];
            status: components["schemas"]["SaleStatus"];
            /** Store Id */
            store_id: number;
            /** Subtotal */
            subtotal: string;
            /** Tax */
            tax: string;
            /** Total */
            total: string;
        };
        /**
         * SaleStatus
         * @description 銷售單狀態。RETURNED 由退貨流程（Phase 4）設定。
         * @enum {string}
         */
        SaleStatus: "COMPLETED" | "RETURNED";
        /**
         * SaleSummaryRead
         * @description 銷售單摘要輸出（列表用，不含明細）。
         */
        SaleSummaryRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            invoice_status: components["schemas"]["SaleInvoiceStatus"];
            status: components["schemas"]["SaleStatus"];
            /** Store Id */
            store_id: number;
            /** Subtotal */
            subtotal: string;
            /** Tax */
            tax: string;
            /** Total */
            total: string;
        };
        /**
         * SerializedItemRead
         * @description 序號品輸出（POS 掃碼查件/庫存列表；不含 acquisition_cost）。
         */
        SerializedItemRead: {
            /** Brand Id */
            brand_id: number | null;
            /** Commission Pct */
            commission_pct: number | null;
            /** Consignor Id */
            consignor_id: number | null;
            grade: components["schemas"]["Grade"];
            /** Id */
            id: number;
            /**
             * Intake Date
             * Format: date-time
             */
            intake_date: string;
            /** Item Code */
            item_code: string;
            /** Listed Price */
            listed_price: string;
            /** Name */
            name: string;
            ownership_type: components["schemas"]["OwnershipType"];
            /** Product Model Id */
            product_model_id: number | null;
            /** Sold Date */
            sold_date: string | null;
            status: components["schemas"]["SerializedItemStatus"];
            /** Store Id */
            store_id: number;
        };
        /**
         * SerializedItemStatus
         * @description 序號品狀態機。
         * @enum {string}
         */
        SerializedItemStatus: "IN_STOCK" | "SOLD" | "RETURNED_TO_CONSIGNOR" | "WRITTEN_OFF";
        /**
         * SettingsRead
         * @description 單店設定輸出。
         */
        SettingsRead: {
            /** Default Commission Pct */
            default_commission_pct: number;
            /** Default Margin Pct */
            default_margin_pct: number;
            /** Einvoice Enabled */
            einvoice_enabled: boolean;
            /** Store Id */
            store_id: number;
            /** Tax Rate */
            tax_rate: string;
        };
        /**
         * SettingsUpdateRequest
         * @description PATCH 設定：所有欄位可選，僅更新有帶入者（exclude_unset）。
         */
        SettingsUpdateRequest: {
            /** Default Commission Pct */
            default_commission_pct?: number | null;
            /** Default Margin Pct */
            default_margin_pct?: number | null;
            /** Einvoice Enabled */
            einvoice_enabled?: boolean | null;
            /** Tax Rate */
            tax_rate?: number | string | null;
        };
        /**
         * TokenResponse
         * @description 登入成功回應：JWT access token（payload 含 sub/role/store_id）。
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createAcquisition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcquisitionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcquisitionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getAcquisition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                acquisition_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcquisitionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listBulkLots: {
        parameters: {
            query?: {
                status?: components["schemas"]["BulkLotStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkLotRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getCurrentCashSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashSessionRead"] | null;
                };
            };
        };
    };
    openCashSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CashSessionOpenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    closeCashSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CashSessionCloseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recordCashMovement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CashMovementCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashMovementRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listCatalogProducts: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogProductRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listContacts: {
        parameters: {
            query?: {
                role?: components["schemas"]["ContactRole"] | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createContact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lookupContact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactLookupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactRead"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getContact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revealContactNationalId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactNationalIdRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listSales: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaleSummaryRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createSale: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaleCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSale: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sale_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    printSaleDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sale_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    voidSale: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sale_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listSerializedItems: {
        parameters: {
            query?: {
                status?: components["schemas"]["SerializedItemStatus"] | null;
                ownership_type?: components["schemas"]["OwnershipType"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SerializedItemRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSerializedItemByCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SerializedItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsRead"];
                };
            };
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getStoreReceiptHeader: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptHeaderRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
